import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Menu,X,Calendar,MapPin,Clock,ArrowRight,ShoppingBag,User,Settings,Plus,Trash2,LogOut,Check,ChevronDown} from 'lucide-react';
import './styles.css';

const services=[
{id:1,name:'60-minute Custom Massage',cat:'Massage',price:85,duration:60,desc:'A personalized Swedish massage with optional deep tissue, cupping or hot stones.'},
{id:2,name:'90-minute Custom Massage',cat:'Massage',price:110,duration:90,desc:'Extended customized bodywork for deeper relaxation and tension relief.'},
{id:3,name:'Ashiatsu/Barefoot Massage 60 Mins',cat:'Massage',price:85,duration:60,desc:'Broad, deep pressure using the therapist’s feet while supported by overhead bars.'},
{id:4,name:'Ashiatsu/Barefoot Massage 90 Mins',cat:'Massage',price:110,duration:90,desc:'Long-form barefoot massage with broad, deep pressure and intentional pacing.'},
{id:5,name:'Reiki',cat:'Wellness',price:25,duration:30,desc:'A non-invasive Japanese energy-healing session focused on relaxation and stress relief.'},
{id:6,name:'Hot Stone Massage',cat:'Massage',price:85,duration:60,desc:'Massage enhanced with hot stones or Himalayan salt stones; advance booking required.'},
{id:7,name:'Chair Massage',cat:'Massage',price:20,duration:10,desc:'A quick, focused relaxation session for busy schedules or events.'},
{id:8,name:'Add On Piercing',cat:'Tattoo',price:45,duration:10,desc:'Piercing add-on available with a 60 or 90 minute massage booking.'}
];
const packages=[['BOGO25 Massage Package — 90 Minutes',192.5,'Two 90-minute massages; second is 25% off.'],['BOGO25 Massage Package — 60 Minutes',148.75,'Two 60-minute massages; second is 25% off.'],['6 Massages & Tattoo Voucher',500,'Six 60-minute massages plus a $150 tattoo voucher.'],['Tattoo & Massage 500',500,'Spend $500 on tattoo work and receive one 60-minute massage.'],['60 Minutes: Buy 2 Get 1 50% Off',212.5,'Buy two massages and receive the third at 50% off.'],['90 Minutes: Buy 2 Get 1 50% Off',275,'Buy two 90-minute massages and receive the third at 50% off.'],['60 Minutes: Buy 4 Get 1 Free',340,'Four 60-minute massages plus one free.'],['90 Minutes: Buy 4 Get 1 Free',440,'Four 90-minute massages plus one free.']];
const members=[['60 Minute Monthly Membership',70,'One 60-minute session each month; unused credits roll over.'],['90 Minute Monthly Membership',95,'One 90-minute session each month; unused credits roll over.']];
const team=[['Chenoa Brown','Licensed Massage & Bodywork Therapist','Deep relaxation, Swedish, Ashiatsu, Reiki, prenatal, cupping, hot stones and more.'],['Matthew Brown','Tattoo Artist','American Traditional-inspired tattoo artist working collaboratively with clients.']];
const hours=[['Monday','Closed'],['Tuesday','4:30 PM – 8 PM'],['Wednesday','4:30 PM – 8 PM'],['Thursday','12 PM – 8 PM'],['Friday','12 PM – 8 PM'],['Saturday','12 PM – 8 PM'],['Sunday','Closed']];

function App(){
 const [page,setPage]=useState(location.hash.slice(1)||'home'); const [menu,setMenu]=useState(false); const [cart,setCart]=useState(()=>JSON.parse(localStorage.getItem('bl_cart')||'[]')); const [book,setBook]=useState(null); const [admin,setAdmin]=useState(false);
 useEffect(()=>{localStorage.setItem('bl_cart',JSON.stringify(cart))},[cart]);
 useEffect(()=>{const f=()=>setPage(location.hash.slice(1)||'home'); addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);
 const nav=(p)=>{location.hash=p;setMenu(false);window.scrollTo(0,0)};
 const add=(item)=>setCart([...cart,{...item,uid:Date.now()}]);
 if(page==='admin') return <Admin onExit={()=>nav('home')}/>;
 return <><Header menu={menu} setMenu={setMenu} nav={nav} cart={cart.length}/><main>
 {page==='home'&&<Home nav={nav} add={add}/>} {page==='services'&&<Services book={setBook}/>} {page==='shop'&&<Shop add={add}/>} {page==='team'&&<Team/>} {page==='about'&&<About nav={nav}/>} {page==='contact'&&<Contact/>} {page==='cart'&&<Cart cart={cart} setCart={setCart} nav={nav}/>} {page==='book'&&<Booking service={book} nav={nav}/>} 
 </main><Footer nav={nav}/>{book&&<Booking service={book} nav={nav} modal onClose={()=>setBook(null)}/>}</>
}
function Header({nav,menu,setMenu,cart}){return <header><a className="logo" onClick={()=>nav('home')}>BLACK<span>LOTUS</span></a><nav className={menu?'open':''}>{[['home','Home'],['services','Services'],['team','Team'],['about','About'],['shop','Shop'],['contact','Contact']].map(x=><a key={x[0]} onClick={()=>nav(x[0])}>{x[1]}</a>)}<button className="bookbtn" onClick={()=>nav('services')}>Book Now</button></nav><div className="headicons"><button onClick={()=>nav('cart')} aria-label="Cart"><ShoppingBag size={19}/>{cart>0&&<b>{cart}</b>}</button><button onClick={()=>setMenu(!menu)} className="mobile"><Menu/></button></div></header>}
function Home({nav,add}){return <>
<section className="hero"><div className="heroShade"/><div className="heroText"><p className="eyebrow">TATTOO • MASSAGE • REIKI</p><h1>Make space for<br/><i>creativity & healing.</i></h1><p className="lead">A comfortable, intentional studio in Lexington, NC where art and bodywork meet.</p><button className="primary" onClick={()=>nav('services')}>Book an appointment <ArrowRight size={17}/></button></div></section>
<section className="intro"><p className="eyebrow">BLACK LOTUS</p><h2>A place to create, restore<br/>and feel at home.</h2><p>We are a permitted tattoo artist and licensed massage therapist team serving Lexington and surrounding areas. Every appointment is built around a partnership with the client.</p><button className="textbtn" onClick={()=>nav('about')}>Our story <ArrowRight size={16}/></button></section>
<section className="split"><div className="photo photo1"/><div className="panel"><p className="eyebrow">BODYWORK</p><h2>Intentional massage.</h2><p>Choose custom massage, Ashiatsu, Reiki, hot stones or chair massage. Sessions are tailored to your needs and goals.</p><button className="primary" onClick={()=>nav('services')}>Explore services</button></div></section>
<section className="dark"><p className="eyebrow">TATTOO</p><h2>Permanent art.<br/><i>Personal meaning.</i></h2><p>From American Traditional inspiration to collaborative custom pieces, bring your next idea into the studio.</p><button className="outline" onClick={()=>nav('contact')}>Start a tattoo conversation</button></section>
<section className="cards"><div><p className="eyebrow">POPULAR</p><h2>Book your next session.</h2></div>{services.slice(0,3).map(s=><ServiceCard key={s.id} s={s} book={()=>location.hash='services'}/>)}</section>
<section className="location"><div><p className="eyebrow">VISIT</p><h2>113 Young Drive<br/>Lexington, NC</h2><p>Massage by appointment. Tattoo walk-ins are welcomed Thursdays, Fridays and Saturdays.</p></div><div className="hours">{hours.map(h=><div key={h[0]}><span>{h[0]}</span><strong>{h[1]}</strong></div>)}</div></section>
</>}
function Services({book}){const [cat,setCat]=useState('All');return <section className="page"><div className="pagehead"><p className="eyebrow">SERVICES</p><h1>Care for your body.<br/><i>Art for your skin.</i></h1><p>Select a service to view details and begin booking.</p></div><div className="filters">{['All','Massage','Wellness','Tattoo'].map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)}>{c}</button>)}</div><div className="servicegrid">{services.filter(s=>cat==='All'||s.cat===cat).map(s=><ServiceCard key={s.id} s={s} book={()=>book(s)}/>)}</div></section>}
function ServiceCard({s,book}){return <article className="service"><div><span>{s.cat}</span><h3>{s.name}</h3><p>{s.desc}</p></div><footer><strong>${s.price}</strong><small>{s.duration} min+</small><button onClick={book}>Select <ArrowRight size={14}/></button></footer></article>}
function Shop({add}){return <section className="page"><div className="pagehead"><p className="eyebrow">SHOP</p><h1>Packages & memberships.</h1><p>Purchase credits now and use them toward eligible sessions.</p></div><h2 className="sectiontitle">Memberships</h2><div className="shopgrid">{members.map((m,i)=><ShopCard key={i} item={{name:m[0],price:m[1],desc:m[2]}} add={add}/>)}</div><h2 className="sectiontitle">Packages</h2><div className="shopgrid">{packages.map((p,i)=><ShopCard key={i} item={{name:p[0],price:p[1],desc:p[2]}} add={add}/>)}</div></section>}
function ShopCard({item,add}){return <article className="shopcard"><span className="eyebrow">BLACK LOTUS</span><h3>{item.name}</h3><p>{item.desc}</p><div><strong>${item.price.toFixed(2)}</strong><button className="primary small" onClick={()=>add(item)}>Add to cart</button></div></article>}
function Team(){return <section className="page"><div className="pagehead"><p className="eyebrow">TEAM</p><h1>People behind<br/><i>the work.</i></h1></div><div className="teamgrid">{team.map((t,i)=><article className="person"><div className={'personphoto p'+i}/><div><p className="eyebrow">{t[1]}</p><h2>{t[0]}</h2><p>{t[2]}</p></div></article>)}</div></section>}
function About({nav}){return <section className="page about"><div className="pagehead"><p className="eyebrow">ABOUT US</p><h1>Creativity and healing<br/><i>in partnership.</i></h1></div><div className="prose"><p>We are a licensed massage therapist and permitted tattoo artist team serving Lexington, NC and the surrounding areas. We aim to provide a comfortable and safe space for creativity and healing by forming a partnership with each client who enters for a service.</p><p>Both artist and therapist have received training in Reiki II and bring that Japanese energy-healing modality to clients interested in stress relief and relaxation.</p><blockquote>“The goal is simple: make every appointment feel intentional, safe and personal.”</blockquote><button className="primary" onClick={()=>nav('services')}>Book now</button></div></section>}
function Contact(){const [sent,setSent]=useState(false);return <section className="page contact"><div><p className="eyebrow">GET IN TOUCH</p><h1>Let's talk<br/><i>about your next idea.</i></h1><p>For tattoo inquiries, collaborations, accessibility questions or booking help, send a message.</p><div className="contactinfo"><p><MapPin/>113 Young Drive, Lexington, NC 27292</p><p><Clock/>Massage by appointment; tattoo walk-ins Thu–Sat</p></div></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}>{sent?<div className="success"><Check/><h2>Message received.</h2><p>This demo form stores no sensitive information and is ready to connect to a real email/API endpoint.</p></div>:<><label>Name<input required/></label><label>Email<input type="email" required/></label><label>Phone<input/></label><label>Message<textarea required rows="6"/></label><button className="primary">Send message</button></>}</form></section>}
function Booking({service,nav,modal,onClose}){const [done,setDone]=useState(false);const [form,setForm]=useState({date:'',time:'',name:'',email:'',phone:'',newClient:true});const submit=e=>{e.preventDefault();const ap=JSON.parse(localStorage.getItem('bl_appointments')||'[]');ap.push({...form,service:service?.name||'Consultation',price:service?.price||0,id:Date.now(),status:'Pending'});localStorage.setItem('bl_appointments',JSON.stringify(ap));setDone(true)};return <div className={modal?'modal':'page booking'}><div className={modal?'modalbox':'bookingbox'}>{modal&&<button className="close" onClick={onClose}><X/></button>}<p className="eyebrow">BOOKING</p>{done?<div className="success"><Check/><h2>Request received.</h2><p>Your appointment is pending confirmation. A $25 new-client deposit applies where required.</p><button className="primary" onClick={()=>{onClose?.();nav('home')}}>Back home</button></div>:<><h1>{service?.name||'Book an appointment'}</h1><form onSubmit={submit} className="bookingform">{service&&<div className="selected"><strong>${service.price}</strong><span>{service.duration} min</span></div>}<label>Preferred date<input type="date" required value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Preferred time<input type="time" required value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/></label><label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Phone<input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="check"><input type="checkbox" checked={form.newClient} onChange={e=>setForm({...form,newClient:e.target.checked})}/> I am a new client</label><button className="primary">Request appointment</button></form></>}</div></div>}
function Cart({cart,setCart,nav}){const total=cart.reduce((a,b)=>a+b.price,0);return <section className="page cartpage"><div className="pagehead"><p className="eyebrow">YOUR CART</p><h1>Ready when<br/><i>you are.</i></h1></div>{!cart.length?<div className="empty"><ShoppingBag size={42}/><h2>Your cart is empty.</h2><button className="primary" onClick={()=>nav('shop')}>Browse packages</button></div>:<><div className="cartitems">{cart.map((x,i)=><div className="cartitem"><div><h3>{x.name}</h3><p>{x.desc}</p></div><strong>${x.price.toFixed(2)}</strong><button onClick={()=>setCart(cart.filter((_,j)=>i!==j))}><Trash2 size={17}/></button></div>)}</div><div className="checkout"><span>Total</span><strong>${total.toFixed(2)}</strong><button className="primary" onClick={()=>alert('Demo checkout: connect Stripe/PayPal in production.')}>Checkout</button></div></>}</section>}
function Footer({nav}){return <footer className="footer"><div><a className="logo">BLACK<span>LOTUS</span></a><p>Tattoo • Massage • Reiki</p></div><div><h4>Explore</h4><a onClick={()=>nav('services')}>Services</a><a onClick={()=>nav('team')}>Team</a><a onClick={()=>nav('shop')}>Shop</a><a onClick={()=>nav('contact')}>Contact</a></div><div><h4>Visit</h4><p>113 Young Drive<br/>Lexington, NC 27292</p><p>Tue–Sat</p></div><div><h4>Hours</h4>{hours.slice(1,6).map(h=><p>{h[0]} · {h[1]}</p>)}</div><button className="adminlink" onClick={()=>nav('admin')}>Admin</button><small>© {new Date().getFullYear()} Black Lotus — demo recreation.</small></footer>}
function Admin({onExit}){const [tab,setTab]=useState('dashboard');const [appointments,setAppointments]=useState(()=>JSON.parse(localStorage.getItem('bl_appointments')||'[]'));const [servicesState,setServicesState]=useState(services);const save=()=>localStorage.setItem('bl_appointments',JSON.stringify(appointments));return <div className="admin"><aside><div className="logo">BLACK<span>LOTUS</span></div><p className="eyebrow">ADMIN</p>{['dashboard','appointments','services','customers','settings'].map(x=><button className={tab===x?'sel':''} onClick={()=>setTab(x)}>{x}</button>)}<button onClick={onExit}><LogOut size={15}/> Exit</button></aside><section className="adminmain"><div className="adminbar"><div><p className="eyebrow">CONTROL CENTER</p><h1>{tab}</h1></div><button onClick={onExit}>View site ↗</button></div>{tab==='dashboard'&&<><div className="stats"><Stat n={appointments.length} t="Appointments"/><Stat n={servicesState.length} t="Services"/><Stat n={packages.length} t="Packages"/><Stat n={members.length} t="Memberships"/></div><div className="admincard"><h2>Recent appointments</h2><AppointmentTable data={appointments.slice(-5).reverse()} set={setAppointments} save={save}/></div></>}{tab==='appointments'&&<div className="admincard"><h2>Appointment management</h2><AppointmentTable data={appointments} set={setAppointments} save={save}/></div>}{tab==='services'&&<div className="admincard"><h2>Services</h2>{servicesState.map((s,i)=><div className="adminrow"><span>{s.name}</span><b>${s.price}</b><button onClick={()=>{const n=[...servicesState];n[i]={...n[i],price:n[i].price+5};setServicesState(n)}}>Increase $5</button></div>)}</div>}{tab==='customers'&&<div className="admincard"><h2>Customers</h2><p>Customers are created from appointment requests in this demo. Connect PostgreSQL/Prisma to persist full customer records.</p><div className="adminrow"><span>Appointment request contacts</span><b>{appointments.length}</b></div></div>}{tab==='settings'&&<div className="admincard"><h2>Studio settings</h2><div className="settingsgrid"><label>Studio name<input defaultValue="Black Lotus Tattoo And Massage"/></label><label>Address<input defaultValue="113 Young Drive, Lexington, NC 27292"/></label><label>New-client deposit<input defaultValue="$25"/></label><label>Cancellation window<input defaultValue="24 hours"/></label></div><button className="primary">Save settings</button></div>}</section></div>}
function Stat({n,t}){return <div className="stat"><strong>{n}</strong><span>{t}</span></div>}
function AppointmentTable({data,set,save}){return <div className="tablewrap"><table><thead><tr><th>Client</th><th>Service</th><th>Date</th><th>Time</th><th>Status</th><th></th></tr></thead><tbody>{data.length?data.map(a=><tr><td>{a.name}<small>{a.email}</small></td><td>{a.service}</td><td>{a.date}</td><td>{a.time}</td><td><select value={a.status} onChange={e=>{const n=JSON.parse(localStorage.getItem('bl_appointments')||'[]').map(x=>x.id===a.id?{...x,status:e.target.value}:x);set(n);localStorage.setItem('bl_appointments',JSON.stringify(n))}}><option>Pending</option><option>Confirmed</option><option>Cancelled</option></select></td><td><button onClick={()=>{const n=JSON.parse(localStorage.getItem('bl_appointments')||'[]').filter(x=>x.id!==a.id);set(n);localStorage.setItem('bl_appointments',JSON.stringify(n))}}><Trash2 size={15}/></button></td></tr>):<tr><td colSpan="6">No appointments yet.</td></tr>}</tbody></table></div>}
createRoot(document.getElementById('root')).render(<App/>);
